build-docker:
  image: docker:23.0.5
  stage: deploy
  services:
    - docker:dind
  variables:
      DOCKER_TLS_CERTDIR: ""
      DOCKER_HOST: "tcp://docker:2375"
  script:
    - docker build -t $DOCKER_USERNAME/frontend:$CI_COMMIT_TAG sys_src/frontend/Dockerfile
    - docker build -t $DOCKER_USERNAME/backend:$CI_COMMIT_TAG sys_src/backend/Dockerfile
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push $DOCKER_USERNAME/frontend:$CI_COMMIT_TAG
    - docker push $DOCKER_USERNAME/backend:$CI_COMMIT_TAG