build-docker:
  image: docker:23.0.5
  stage: deploy
  services:
    - docker:dind
  variables:
      DOCKER_TLS_CERTDIR: ""
      DOCKER_HOST: "tcp://docker:2375"
  script:
    - cd sys_src/frontend/
    - docker build -t $DOCKER_USERNAME/bdcc-team-blau:frontend-$CI_COMMIT_TAG .
    - cd ../../sys_src/backend/
    - docker build -t $DOCKER_USERNAME/bdcc-team-blau:backend-$CI_COMMIT_TAG .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push $DOCKER_USERNAME/bdcc-team-blau:frontend-$CI_COMMIT_TAG
    - docker push $DOCKER_USERNAME/bdcc-team-blau:backend-$CI_COMMIT_TAG