lint-js:
  stage: validate
  script:
    - npm install -g eslint
    - eslint sys_src/frontend --ext .js,.jsx,.ts,.tsx
  rules:
    - changes:
      - sys_src/frontend/**/*
  allow_failure: true

build-js:
  stage: build
  image: node:latest
  script:
    - cd sys_src/frontend/NauticalNonsense
    - npm build
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/
  rules:
    - changes:
      - sys_src/frontend/**/*

coverage-js:
  stage: test
  image: node:latest
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
    - build
  script:
    - cd sys_src/frontend/NauticalNonsense
    - npm test
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  rules:
    - changes:
      - sys_src/frontend/**/*
