lint-js:
  stage: validate
  image: node:latest
  script:
    - cd sys_src/frontend/NauticalNonsense
    - npm install -g eslint
    - npm init @eslint/config
    - eslint --ext .js,.jsx,.ts,.tsx
  # rules:
  #   - changes:
  #     - sys_src/frontend/**/*
  allow_failure: true

build-js:
  stage: build
  image: node:latest
  script:
    - cd sys_src/frontend/NauticalNonsense
    - npm install
  cache:
    paths:
      - sys_src/frontend/NauticalNonsense/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - sys_src/frontend/NauticalNonsense/node_modules/
  # rules:
  #   - changes:
  #     - sys_src/frontend/**/*

coverage-js:
  stage: test
  image: node:latest
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
    - build-js
  script:
    - cd sys_src/frontend/NauticalNonsense
    - npm test
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  # rules:
  #   - changes:
  #     - sys_src/frontend/**/*
