lint:
  image: python:3.11-slim
  stage: lint
  before_script:
    - pip install ruff black
  script:
    - black sys_src/backend --check --verbose --diff --color
    - ruff sys_src/backend
  rules:
    - changes:
      - sys_src/backend/**/*

coverage:
  image: python:3.11-slim
  stage: test
  before_script:
    - pip install -r sys_src/backend/requirements.txt
    - pip install pytest pytest-cov
  script:
    - pytest --cov=sys_src/backend/ --cov-report xml --junitxml=report.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
  rules:
    - changes:
      - sys_src/backend/**/*
