# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.gitlab-ci.yml

include:
  - template: Terraform/Base.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.gitlab-ci.yml
  # - template: Jobs/SAST-IaC.gitlab-ci.yml   # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/SAST-IaC.gitlab-ci.yml

image:
  name: "$CI_TEMPLATE_REGISTRY_HOST/gitlab-org/terraform-images/releases/1.4:v1.0.0"

variables:
  TF_ROOT: sys_src/infrastructure

.get_ca_certificate:
  before_script:
    - apk add openssl sudo
    - CERT_NAME=OTH-GIT
    - URL=git.oth-aw.de
    - openssl s_client -connect $URL:443  -showcerts < /dev/null 2>/dev/null > $CERT_NAME.crt
    - openssl x509 -inform PEM -in $CERT_NAME.crt -out $CERT_NAME.crt
    - sudo mv $CERT_NAME.crt /usr/local/share/ca-certificates
    - sudo update-ca-certificates

fmt:
  extends: .terraform:fmt
  needs: []

validate:
  extends: 
    - .terraform:validate
    - .get_ca_certificate
  needs: []

build:
  extends: 
    - .terraform:build
    - .get_ca_certificate

deploy:
  extends: 
    - .terraform:deploy
    - .get_ca_certificate
  dependencies:
    - build
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH 
      when: manual
  environment:
    name: $TF_STATE_NAME
  artifacts:
    paths:
      - ${TF_ROOT}/kubeconfig_bdcc-team-blau

test:
  image: 
    name: bitnami/kubectl
    entrypoint: [""] # override the entrypoint so we can use kubectl
  dependencies:
    - deploy
  script:
    - mv ${TF_ROOT}/kubeconfig_bdcc-team-blau ${TF_ROOT}/test/kubeconfig_bdcc-team-blau
    - cd sys_src/infrastructure/test
    - KUBECONFIG=./kubeconfig_bdcc-team-blau
    - kubectl apply -f deployment.yaml
    - kubectl get pods
    - kubectl apply -f service.yaml
    - kubectl apply -f ingress.yaml

destroy:
  extends: 
    - .terraform:destroy
    - .get_ca_certificate
