include:
  - local: sys_src/templates/terraform.gitlab-ci.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - local: sys_src/templates/python.gitlab-ci.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "push"
  - local: sys_src/templates/js.gitlab-ci.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "push"
  - local: sys_src/templates/docker.gitlab-ci.yml
    rules:
      - if: $CI_COMMIT_TAG
  - local: sys_src/templates/deploy.gitlab-ci.yml
    rules:
      - if: $CI_COMMIT_TAG

stages:
  - validate
  - lint
  - build
  - unit-test
  - deploy
  - prepare-test
  - integration-test
  - post-test
  - deploy-dashboard
  - cleanup
    
dummy:
  stage: .pre
  script:
    - echo $CI_PIPELINE_SOURCE