include:
  - local: sys_src/templates/terraform.gitlab-ci.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "web"
  - local: sys_src/templates/python.gitlab-ci.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "push"
  - local: sys_src/templates/docker.gitlab-ci.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "push"

dummy:
  stage: .pre
  script:
    - echo $CI_PIPELINE_SOURCE