include:
  - local: sys_templates/terraaform.gitlab-ci.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "web"
  - local: sys_templates/python.gitlab-ci.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "push"